# Version of the Icarus theme that is currently used
version: 2.6.0
# Path or URL to the website's icon
favicon: # see 'head.ejs' for detail
# Additional HTML meta tags in an array.
meta: 
# canonical_url of your site
canonical_url: https://duinomaker.top/
# Path or URL to RSS atom.xml
rss:
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
# logo: /images/logo.svg
logo: https://cdn.jsdelivr.net/gh/duinomaker/HexoBlog@d638cb1/source/images/misc/logo.svg

# Open Graph metadata
# https://hexo.io/docs/helpers.html#open-graph
open_graph:
    # Facebook App ID
    # fb_app_id: '118489899585369'
    # Facebook Admin ID
    fb_admins: '100043022235251'
    # Twitter ID
    twitter_id: 'duinomaker'
    # Twitter site
    twitter_site: '@duinomaker'
    # Google+ profile link
    # google_plus: 

# Navigation bar link settings
navbar:
    # Navigation bar menu links
    menu:
        Home: /
        Archives: /archives/
        Categories: /categories/
        Notes: /notes/
        # Tags: /tags/
        About: /about/
    # Navigation bar links to be shown on the right
    # links:
    #     Download on GitHub:
    #         icon: fab fa-github
    #         url: 'https://github.com/ppoffice/hexo-theme-icarus'

# Footer section link settings
# footer:
#     Links to be shown on the right of the footer section
#     links:
#         Creative Commons:
#             icon: fab fa-creative-commons
#             url: 'https://creativecommons.org/'
#         Attribution 4.0 International:
#             icon: fab fa-creative-commons-by
#             url: 'https://creativecommons.org/licenses/by/4.0/'
#         NonCommercial 4.0 International:
#             icon: fab fa-creative-commons-nc
#             url: 'https://creativecommons.org/licenses/nc/4.0/'
#         ShareAlike 4.0 International:
#             icon: fab fa-creative-commons-sa
#             url: 'https://creativecommons.org/licenses/sa/4.0/'
#         CC:
#             icon: /images/cc-by-nc-sa.svg
#             url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Article display settings
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # Show code copying button
        clipboard: false
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show article thumbnail images
    thumbnail: false
    # Whether to show estimate article reading time
    readtime: false

# Search plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search
search:
    # Name of the search plugin
    type: insight

# Comment plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment
comment:
    type: valine
    app_id: jUDJCYuOij3UzEzFmRpQer5U-gzGzoHsz   # (required) LeanCloud application id
    app_key: h2AVOMeF8QsLYFdVVbbf9d7k           # (required) LeanCloud application key
    notify: false               # (optional) receive email notification
    verify: false               # (optional) show verification code
    placeholder: Suggestions are welcome. # (optional) comment box placeholder text
    lang: en

# Donation entries
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
# donate:
#     -
#         # Donation entry name
#         type: alipay
#         # Qrcode image URL
#         qrcode: ''
#     -
#         # Donation entry name
#         type: wechat
#         # Qrcode image URL
#         qrcode: ''
#     -
#         # Donation entry name
#         type: paypal
#         # Paypal business ID or email address
#         business: ''
#         # Currency code
#         currency_code: USD
#     -
#         # Donation entry name
#         type: patreon
#         # URL to the Patreon page
#         url: ''

# Share plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share
share:
    # Share plugin name
    type: 
# Sidebar settings.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # left sidebar settings
    left:
        # Whether the left sidebar is sticky when page scrolls
        # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
    # right sidebar settings
    right:
        # Whether the right sidebar is sticky when page scrolls
        # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
# Sidebar widget settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    -
        # Widget name
        type: toc
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: profile
        # Where should the widget be placed, left or right
        position: left
        # Author name to be shown in the profile widget
        author: duinomaker
        # Title of the author to be shown in the profile widget
        author_title: NJUPT
        # Author's current location to be shown in the profile widget
        location: Jiangsu, China
        # Path or URL to the avatar to be shown in the profile widget
        # avatar: /images/avatar.jpg
        avatar: https://cdn.jsdelivr.net/gh/duinomaker/HexoBlog@d638cb1/source/images/misc/avatar.jpg
        # Email address for the Gravatar to be shown in the profile widget
        gravatar: 
        # Whether to show avatar image rounded or square
        avatar_rounded: true
        # Path or URL for the follow button
        follow_link: 'https://github.com/duinomaker'
        # Links to be shown on the bottom of the profile widget
        # social_links:
            # Github:
            #     icon: fab fa-github
            #     url: 'https://github.com/duinomaker'
            # E-Mail:
            #     icon: fas fa-envelope
            #     url: 'mailto:duinomaker@gmail.com'
            # Facebook:
            #     icon: fab fa-facebook
            #     url: 'https://facebook.com'
            # Twitter:
            #     icon: fab fa-twitter
            #     url: 'https://twitter.com/duinomaker'
            # RSS:
            #     icon: fas fa-rss
            #     url: /atom.xml
    -
        # Widget name
        type: links
        # Where should the widget be placed, left or right
        position: left
        # Links to be shown in the links widget
        links:
            0xfaner: 'https://0xfaner.top/'
            Brethland: 'https://yuki.systems/'
            matrix72: 'https://www.matrix72.top/'
            xjzsq: 'https://www.xjdesyxx.top/'
            故心人不见: 'https://yuhi.xyz/'
            雨落新痕: 'https://mashiro.zone/'
            
    -
        # Widget name
        type: category
        # Where should the widget be placed, left or right
        position: left
    # -
    #     # Widget name
    #     type: tagcloud
    #     # Where should the widget be placed, left or right
    #     position: left
    # -
    #     # Widget name
    #     type: recent_posts
    #     # Where should the widget be placed, left or right
    #     position: left
    # -
    #     # Widget name
    #     type: archive
    #     # Where should the widget be placed, left or right
    #     position: left
    -
        # Widget name
        type: tag
        # Where should the widget be placed, left or right
        position: left

# Other plugin settings
plugins:
    # Enable page animations
    animejs: false
    # Enable the lightGallery and Justified Gallery plugins
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
    gallery: false
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated-browser: false
    # Enable the MathJax plugin
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/mathjax-plugin/
    mathjax: false
    katex: false
    # Show the back to top button on mobile devices
    back-to-top: false
    # # Google Analytics plugin settings
    # # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Google-Analytics
    # google-analytics:
    #     # Google Analytics tracking id
    #     tracking_id: UA-158094635-1
    # # Baidu Analytics plugin settings
    # # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Baidu-Analytics
    # baidu-analytics:
    #     # Baidu Analytics tracking id
    #     tracking_id: d65d8f50e178d8d3b878eea462f261d9
    # # Hotjar user feedback plugin
    # # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Hotjar
    # hotjar:
    #     # Hotjar site id
    #     site_id: 1679883
    # Show a loading progress bar at top of the page
    progressbar: false
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: false
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL of the webfont CDN provider
    fontcdn: google
    # Name or URL of the webfont Icon CDN provider
    # iconcdn: fontawesome
    # iconcdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css
    # iconcdn: 'https://cdn.bootcss.com/font-awesome/5.13.0/css/all.min.css'
    # iconcdn: /fonts/font-awesome/all.min.css
    iconcdn: 'https://cdn.jsdelivr.net/gh/duinomaker/HexoBlog@d638cb1/assets/font-awesome/all.min.css'
